version: "3.8"

services:
  babershop:
    build: .
    container_name: babershop
    ports:
      - "5000:5000"
    volumes:
      - ./babershop:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia